name: 🐞 Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: [bug, needs-triage]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill out the form below as completely as possible.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the issue.
      placeholder: "e.g., App crashes when saving a file"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the bug is.
      placeholder: "When I do X, I expect Y, but instead Z happens."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: "The app should save without crashing."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide environment details where the issue occurs.
      placeholder: "OS: macOS 14.5, Node v20.10.0, Browser: Chrome 128"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Paste relevant log output or error messages.
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the issue?
      options:
        - 🟢 Minor (Cosmetic or low impact)
        - 🟡 Moderate (Affects some functionality)
        - 🔴 Critical (Breaks core functionality)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / Screenshots
      description: Add any other context or screenshots about the problem here.
