name: 💡 Feature Request / Idea
description: Suggest a new feature, enhancement, or idea
title: "[Feature]: "
labels: [enhancement, idea]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or improvement! Please provide as much context as possible to help us evaluate it.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence summary of your idea.
      placeholder: "e.g., Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or need your feature would solve.
      placeholder: "Users currently have to..., which makes it hard to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / Feature
      description: Explain how you’d like the feature to work.
      placeholder: "A toggle in settings that allows users to switch themes."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions or workarounds you've tried or considered.
      placeholder: "Currently, users can manually edit config.json, but it’s not user-friendly."

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you or your workflow?
      options:
        - 🟢 Nice to have
        - 🟡 Important
        - 🔴 Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / References
      description: Add any other context, mockups, screenshots, or references that help explain your idea.
